//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGCONG
    {
        public int MABC { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> DAY { get; set; }
        public Nullable<int> GIOBAO { get; set; }
        public Nullable<int> PHUTVAO { get; set; }
        public Nullable<int> GIORA { get; set; }
        public Nullable<int> PHUTRA { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> IDLC { get; set; }
    
        public virtual TB_LOAICONG TB_LOAICONG { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
